Allow context_from_plack_request to bubble up custom HTTP responses.
pobox/Ix pull request #33
Opened 2016-09-20 15:52 UTC by wolfsage

For example, if it fails to find a session, it may want to throw a
401 response.

2016-09-20 15:53 UTC, wolfsage commented on t/lib/Bakesale/Context.pm
> +
I figure most cases will look like the above - we want to return a specific http response code and nothing more

2016-09-20 15:53 UTC, wolfsage commented on t/lib/Bakesale/Context.pm
> +
This case is if we want to specify a specific body, or more likely, nuke the user's cookies

2016-09-21 17:49 UTC, rjbs commented on lib/Ix/App.pm
> +    try {
Discussed on Slack.  This should be moved up into App's general "big eval wrapper" so the "handle HTTP::Exceptions?" comment becomes code.

2016-09-21 17:49 UTC, rjbs requested changes
Looks good, modulo the one change called out and discussed.

2016-09-21 18:20 UTC, rjbs approved these changes

2016-09-21 18:21 UTC, merged