ix_updated: new semantics, provide unified old/new value has
pobox/Ix pull request #52
Opened 2017-01-06 18:56 UTC by rjbs

As discussed, I think this interface will end up being easier in the future.

2017-01-06 19:10 UTC, wolfsage requested changes
2 nits, otherwise +1

2017-01-06 19:10 UTC, wolfsage commented on lib/Ix/DBIC/ResultSet.pm
> +        if (%new && (my $code = $rclass->can('ix_updated'))) {
`if (%new &&` is unnecessary at this point

2017-01-06 19:10 UTC, wolfsage commented on lib/Ix/DBIC/ResultSet.pm
> +        if (%new && (my $code = $rclass->can('ix_updated'))) {
Also no reason to take `my $code` if we aren't using it

2017-01-07 01:34 UTC, rjbs commented on lib/Ix/DBIC/ResultSet.pm
> +        if (%new && (my $code = $rclass->can('ix_updated'))) {
Thanks, I'll fix these.

2017-01-17 19:56 UTC, rjbs commented
I believe this addresses the nits.  Will have to coordinate this rollout.

2017-01-23 20:04 UTC, merged

2017-01-23 20:43 UTC, rjbs commented
Merged, rolled out.